### ISSUE TITLE
Composer library should not contain composer.lock due to unmeet expectations.

### ISSUE THREAD

**Issue by DannyvdSluijs** [FeastFramework/json#1]
As mentioned in the [docs](https://getcomposer.org/doc/02-libraries.md#lock-file) the lock file wont have the effect you think it would have.
>For your library you may commit the composer.lock file if you want to. This can help your team to always test against the same dependency versions. However, this lock file will not have any effect on other projects that depend on it. It only has an effect on the main project.

**Comment by jpresutti** [comment]
The only dependency is psalm/phar for static type analysis. It is used by Github actions and is version locked for running the tool with the appropriate version developed against. This is intentional.
